name: agenda
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  sqflite: ^1.1.7+3
  path_provider: ^1.4.5
  intl: ^0.16.0
  flutter_datetime_picker: 1.2.5
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  permission_handler: ^4.0.0
  contacts_service: ^0.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
